version: 0.0
os: linux
files:
  - source: source/server/app
    destination: /home/ubuntu/wavetowww/source/server/app
  - source: source/kernel
    destination: /home/ubuntu/wavetowww/source/kernel
  - source: scripts
    destination: /home/ubuntu/wavetowww/scripts
  - source: appspec.yml
    destination: /home/ubuntu/wavetowww/appspec.yml

hooks:
  BeforeInstall:
    - location: scripts/copy_env.sh
      timeout: 60
      runas: ubuntu
    - location: scripts/stop_docker.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_docker.sh
      timeout: 180
      runas: ubuntu
  ValidateService:
    - location: scripts/validate.sh
      timeout: 600
      runas: ubuntu
