version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/wavetowww

hooks:
  BeforeInstall:
    - location: scripts/stop_docker.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: ubuntu
