name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Build Docker image
        run: |
          docker build -t wavetowww -f ./server/Dockerfile ./server

      - name: Package application
        run: |
          zip -r deploy-package.zip appspec.yml scripts/

      - name: Upload to S3
        run: |
          aws s3 cp deploy-package.zip s3://wavetowww-bucket/

      - name: Create CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name wavetowww \
            --deployment-group-name wavetowww-deploy-group \
            --s3-location bucket=wavetowww-bucket,key=deploy-package.zip,bundleType=zip
